services:
  mysql:
    image: mysql:8.0
    container_name: mysql_db
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: game_db
      MYSQL_USER: game_user
      MYSQL_PASSWORD: game_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql  # Monta el archivo SQL
    networks:
      - game_network

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "8081:8080"
    depends_on:
      - mysql
    networks:
      - game_network

  #node_server:
   # build: ./server
    #container_name: node_server
    #ports:
    #  - "3000:3000"
    #depends_on:
    #  - mysql
    #environment:
    #  DB_HOST: mysql
    #  DB_USER: game_user
    #  DB_PASSWORD: game_password
    #  DB_NAME: game_db
    #networks:
    #  - game_network

volumes:
  mysql_data:

networks:
  game_network: